### ISSUE TITLE
Windows 7: Tor service no started. You need started this to execute this option.

### ISSUE THREAD

**Issue by Shazgul** [magichk/magicleaks#10]
Hey magicleaks Dev,

I've expecting the Error "Tor service no started. You need started this to execute this option." meanwhile the tor32 Service is installed via `tor.exe -service install` under Windows 7 and services.msc says that it is running.
What actually i'm doing wrong, that it's still shown as not started?

**Comment by magichk** [comment]
The tools is for Linux but maybe in next days I can fix it for windows. 

Thanks :)

magichk

**Comment by magichk** [comment]
I did it an initial support for Windows (I make a new commit) but the tool is for linux environments. 

In the future I will be adapt new features to Windows environments.

Thanks.
