### ISSUE TITLE
Error desconocido al ejecutar desde una Kali en Virtualbox

### ISSUE THREAD

**Issue by gfmateo** [magichk/magicleaks#13]
Buenas tardes,

Al ejecutar la herramienta desde una Kali en VirtualBox (con 2 GB de memoria), al intentar el análisis de cualquier dominio con -d, se "bloquea" la herramienta y acaba siempre dando el error "Error: unknow error". Pasa con cualquier dominio. Con emails concretos sin problema, sólo con el módulo de dominios. ¿A qué se puede deber el error?

gracias

**Comment by BinaryShadow94** [comment]
Buenas tardes,


Gracias por notificar el error.

La busqueda por dominios se realiza utilizando el servicio "pwndb", el cual actualmente esta fuera de servicio, estamos estudiando alternativas para cuando sucede esto.

![imagen](https://user-images.githubusercontent.com/26254187/131893839-57fc5559-2d64-4ec8-97fe-29ab0051ac72.png)

Se va a capturar el error y especificar que la busqueda por dominios no está disponible en este momento al no estar el servicio pwndb disponible.

Un saludo.

**Comment by BinaryShadow94** [comment]
Hoy vuelve a estar disponible pwndb, por lo que la funcionalidad de búsqueda por dominios ya funciona correctamente.
Si sigues teniendo el mismo error reabre la incidencia para que podamos investigar la razón de la misma.
